# Generated by Django 2.2.2 on 2019-07-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '等待批准'), (1, ' 批准 '), (2, ' 拒绝')], default=0, verbose_name='状态'),
        ),
    ]
